import Foundation

/// Pure Swift port of the server's promote-preview shaping logic (offline
/// support plan Phase 11), used by `LocalMemoDataSource` in Standalone mode.
///
/// Source of truth being mirrored:
/// - `buildPromoteBody` in `packages/db/src/memoRepository.ts` — memo body
///   plus a `## コメント` section inlining every live comment.
/// - the link-row mapping inside `getPromotePreview` (same file) — direction,
///   `unknown` type fallback, and the 80-unit whitespace-collapsed title
///   fallback taken from the target's body.
///
/// Issue-mention rewriting (`packages/core/src/issueMentions.ts`) is NOT part
/// of promote: the server applies it when bodies are written, so stored
/// bodies already carry rewritten links and promotePreview never touches it.
///
/// Everything here is DB-independent: `LocalMemoDataSource` assembles the
/// inputs from GRDB and this type only shapes them, so unit tests can assert
/// byte-for-byte parity with outputs generated by the TypeScript original.
nonisolated enum PromoteEngine {
    // MARK: - Body building

    /// One comment as the body builder needs it (`created_at` ASC order is
    /// the caller's responsibility, mirroring `listComments`).
    struct CommentInput: Equatable {
        let createdAt: String
        let bodyMd: String

        init(createdAt: String, bodyMd: String) {
            self.createdAt = createdAt
            self.bodyMd = bodyMd
        }
    }

    /// Port of `buildPromoteBody(baseBody, comments)`:
    ///
    /// ```
    /// <baseBody>            // only when non-empty
    ///
    /// ---
    /// ## コメント
    ///
    /// ### <comment.createdAt>
    /// <comment.bodyMd>
    /// ...
    /// ```
    /// joined with "\n" and trimmed at both ends (JS `String.trim`).
    static func buildPromoteBody(baseBody: String, comments: [CommentInput]) -> String {
        var parts: [String] = []

        // JS: `if (baseBody)` — the empty string is the only falsy String.
        if !baseBody.isEmpty {
            parts.append(baseBody)
        }

        if !comments.isEmpty {
            parts.append("")
            parts.append("---")
            parts.append("## コメント")
            parts.append("")

            for comment in comments {
                parts.append("### \(comment.createdAt)")
                parts.append(comment.bodyMd)
                parts.append("")
            }
        }

        return jsTrim(parts.joined(separator: "\n"))
    }

    // MARK: - Linked-issue mapping

    /// One raw link row exactly as the TS query surfaces it: integer issue
    /// ids on both ends plus the LEFT-JOINed target columns (nil when the
    /// counterpart row is missing).
    struct LinkRow {
        let sourceIssueId: Int
        let targetIssueId: Int
        let linkType: String
        let targetType: String?
        let targetTitle: String?
        let targetBody: String?

        init(
            sourceIssueId: Int,
            targetIssueId: Int,
            linkType: String,
            targetType: String?,
            targetTitle: String?,
            targetBody: String?
        ) {
            self.sourceIssueId = sourceIssueId
            self.targetIssueId = targetIssueId
            self.linkType = linkType
            self.targetType = targetType
            self.targetTitle = targetTitle
            self.targetBody = targetBody
        }
    }

    /// Shaped link entry, field-for-field what the server puts in
    /// `linkedIssues[]` (flattened; the caller wraps `target*` into its
    /// response model).
    struct LinkedIssue: Equatable {
        let direction: String // "outgoing" | "incoming"
        let linkType: String
        let targetId: Int
        let targetType: String
        let targetTitle: String
    }

    /// Port of the `linkRows.map(...)` block in `getPromotePreview`.
    static func linkedIssues(memoId: Int, rows: [LinkRow]) -> [LinkedIssue] {
        rows.map { row in
            let isOutgoing = row.sourceIssueId == memoId
            let targetId = isOutgoing ? row.targetIssueId : row.sourceIssueId
            let title: String
            if let explicit = row.targetTitle, !explicit.isEmpty {
                title = explicit
            } else {
                title = fallbackTitle(fromBody: row.targetBody)
            }
            return LinkedIssue(
                direction: isOutgoing ? "outgoing" : "incoming",
                linkType: row.linkType,
                targetId: targetId,
                targetType: row.targetType ?? "unknown",
                targetTitle: title
            )
        }
    }

    /// Port of `(body ?? '').replace(/\s+/g, ' ').trim().slice(0, 80)` — the
    /// title shown for targets without an explicit title (memos, articles).
    ///
    /// `slice(0, 80)` counts UTF-16 code units like JavaScript. The only
    /// deviation: when unit 80 falls inside a surrogate pair or grapheme
    /// cluster we round DOWN to the previous character boundary, because a
    /// Swift String cannot hold the lone surrogate JS would produce.
    static func fallbackTitle(fromBody body: String?) -> String {
        sliceUTF16(jsTrim(collapseWhitespace(body ?? "")), maxUnits: 80)
    }

    // MARK: - JS string-semantics helpers

    /// Scalars matched by JavaScript's `\s` (WhiteSpace + LineTerminator):
    /// TAB VT FF SP NBSP ZWNBSP, LF CR LS PS, and the Unicode Zs category.
    private static let jsWhitespace: Set<Unicode.Scalar> = [
        "\u{0009}", "\u{000A}", "\u{000B}", "\u{000C}", "\u{000D}",
        "\u{0020}", "\u{00A0}", "\u{1680}",
        "\u{2000}", "\u{2001}", "\u{2002}", "\u{2003}", "\u{2004}",
        "\u{2005}", "\u{2006}", "\u{2007}", "\u{2008}", "\u{2009}",
        "\u{200A}", "\u{2028}", "\u{2029}", "\u{202F}", "\u{205F}",
        "\u{3000}", "\u{FEFF}",
    ]

    /// `replace(/\s+/g, ' ')` — collapse every whitespace run to one space.
    private static func collapseWhitespace(_ string: String) -> String {
        var result = String.UnicodeScalarView()
        var inRun = false
        for scalar in string.unicodeScalars {
            if jsWhitespace.contains(scalar) {
                if !inRun {
                    result.append("\u{0020}")
                    inRun = true
                }
            } else {
                result.append(scalar)
                inRun = false
            }
        }
        return String(result)
    }

    /// JS `String.prototype.trim` (strips `\s` from both ends).
    private static func jsTrim(_ string: String) -> String {
        let scalars = string.unicodeScalars
        var start = scalars.startIndex
        while start < scalars.endIndex, jsWhitespace.contains(scalars[start]) {
            start = scalars.index(after: start)
        }
        var end = scalars.endIndex
        while end > start {
            let before = scalars.index(before: end)
            if jsWhitespace.contains(scalars[before]) {
                end = before
            } else {
                break
            }
        }
        return String(String.UnicodeScalarView(scalars[start..<end]))
    }

    /// `slice(0, maxUnits)` counting UTF-16 code units, rounding down to a
    /// character boundary (see `fallbackTitle`).
    private static func sliceUTF16(_ string: String, maxUnits: Int) -> String {
        var used = 0
        var end = string.startIndex
        var index = string.startIndex
        while index < string.endIndex {
            let units = string[index].utf16.count
            if used + units > maxUnits {
                break
            }
            used += units
            index = string.index(after: index)
            end = index
        }
        return String(string[..<end])
    }
}
