import XCTest
@testable import MemeGTD

/// Phase 11 parity coverage: `PromoteEngine` must produce byte-for-byte the
/// same output as the TypeScript original (`buildPromoteBody` and the link
/// mapping in `getPromotePreview`, packages/db/src/memoRepository.ts).
///
/// Test data comes from two places:
/// - direct ports of the TS test cases (packages/db/test/memoRepository.test.ts,
///   packages/core/test/memoService.test.ts,
///   packages/api/test/integration/memos.test.ts), and
/// - expected strings GENERATED BY RUNNING THE TS IMPLEMENTATION itself
///   (node against packages/db/dist/memoRepository.js), so every exact-match
///   assertion below is anchored to real TypeScript output, not to a reading
///   of the code.
final class PromoteEngineTests: XCTestCase {
    private func comment(_ createdAt: String, _ bodyMd: String) -> PromoteEngine.CommentInput {
        PromoteEngine.CommentInput(createdAt: createdAt, bodyMd: bodyMd)
    }

    // MARK: - buildPromoteBody: TS test ports

    /// packages/api/test/integration/memos.test.ts
    /// "should return just memo body when there are no comments"
    func testBodyOnlyIsReturnedVerbatim() {
        XCTAssertEqual(
            PromoteEngine.buildPromoteBody(baseBody: "Lonely memo", comments: []),
            "Lonely memo"
        )
    }

    /// packages/db/test/memoRepository.test.ts
    /// "promote preview returns memo body and labels" (body assertion)
    func testDraftTaskBodyMatchesDbRepositoryCase() {
        XCTAssertEqual(
            PromoteEngine.buildPromoteBody(baseBody: "draft task", comments: []),
            "draft task"
        )
    }

    /// packages/core/test/memoService.test.ts "MemoService promotePreview"
    func testPromoteMeBodyMatchesCoreServiceCase() {
        XCTAssertEqual(
            PromoteEngine.buildPromoteBody(baseBody: "promote me", comments: []),
            "promote me"
        )
    }

    /// packages/api/test/integration/memos.test.ts
    /// "should return memo body with comments inlined". The TS test only
    /// asserts `includes(...)`; the exact string here is the TS
    /// implementation's real output for these inputs.
    func testBodyWithTwoCommentsInlined() {
        let body = PromoteEngine.buildPromoteBody(
            baseBody: "Preview memo body",
            comments: [
                comment("2026-07-01T10:00:00.000Z", "thought A"),
                comment("2026-07-01T11:30:00.000Z", "thought B"),
            ]
        )

        // The TS test's own assertions:
        XCTAssertTrue(body.contains("Preview memo body"))
        XCTAssertTrue(body.contains("## コメント"))
        XCTAssertTrue(body.contains("thought A"))
        XCTAssertTrue(body.contains("thought B"))

        // Exact TS output:
        XCTAssertEqual(
            body,
            "Preview memo body\n\n---\n## コメント\n\n### 2026-07-01T10:00:00.000Z\nthought A\n\n### 2026-07-01T11:30:00.000Z\nthought B"
        )
    }

    // MARK: - buildPromoteBody: edge cases (expected strings from TS runs)

    func testEmptyBodyWithCommentDropsBodyAndLeadingBlank() {
        XCTAssertEqual(
            PromoteEngine.buildPromoteBody(
                baseBody: "",
                comments: [comment("2026-07-02T09:00:00.000Z", "only comment")]
            ),
            "---\n## コメント\n\n### 2026-07-02T09:00:00.000Z\nonly comment"
        )
    }

    func testEmptyBodyNoCommentsIsEmpty() {
        XCTAssertEqual(PromoteEngine.buildPromoteBody(baseBody: "", comments: []), "")
    }

    func testMultilineMarkdownAndSpecialCharactersSurviveUnchanged() {
        XCTAssertEqual(
            PromoteEngine.buildPromoteBody(
                baseBody: "# Title\n\n- item `#12`\n> quote \"quoted\" \\#5",
                comments: [
                    comment("2026-07-03T00:00:00.000Z", "line1\nline2\n\n```\ncode #7\n```"),
                    comment("2026-07-03T01:00:00.000Z", "日本語のコメント 🎯"),
                ]
            ),
            "# Title\n\n- item `#12`\n> quote \"quoted\" \\#5\n\n---\n## コメント\n\n### 2026-07-03T00:00:00.000Z\nline1\nline2\n\n```\ncode #7\n```\n\n### 2026-07-03T01:00:00.000Z\n日本語のコメント 🎯"
        )
    }

    func testTrailingBodyWhitespaceKeptInsideButTrimmedAtEnds() {
        XCTAssertEqual(
            PromoteEngine.buildPromoteBody(
                baseBody: "body with trailing newline\n\n",
                comments: [comment("2026-07-03T02:00:00.000Z", "c1")]
            ),
            "body with trailing newline\n\n\n\n---\n## コメント\n\n### 2026-07-03T02:00:00.000Z\nc1"
        )
    }

    // MARK: - fallbackTitle (TS: (body ?? '').replace(/\s+/g, ' ').trim().slice(0, 80))

    func testFallbackTitleCollapsesAndTrimsWhitespace() {
        XCTAssertEqual(
            PromoteEngine.fallbackTitle(fromBody: "  line1\n line2\t\ttab   spaces  "),
            "line1 line2 tab spaces"
        )
    }

    func testFallbackTitleTruncatesTo80Units() {
        XCTAssertEqual(
            PromoteEngine.fallbackTitle(fromBody: String(repeating: "a", count: 100)),
            String(repeating: "a", count: 80)
        )
    }

    func testFallbackTitleHandlesJapaneseAndIdeographicSpace() {
        XCTAssertEqual(
            PromoteEngine.fallbackTitle(fromBody: "日本語　全角スペース　改行\nあり"),
            "日本語 全角スペース 改行 あり"
        )
    }

    func testFallbackTitleNilBodyIsEmpty() {
        XCTAssertEqual(PromoteEngine.fallbackTitle(fromBody: nil), "")
    }

    // MARK: - linkedIssues mapping

    /// packages/api/test/integration/memos.test.ts
    /// "should include outgoing and incoming links with target issue info"
    /// (outgoing half; the memo target has no title so the body fallback
    /// applies, matching the TS `title.length > 0` assertion).
    func testOutgoingLinkMapsDirectionTypeAndFallbackTitle() {
        let mapped = PromoteEngine.linkedIssues(
            memoId: 1,
            rows: [
                PromoteEngine.LinkRow(
                    sourceIssueId: 1,
                    targetIssueId: 2,
                    linkType: "relates",
                    targetType: "memo",
                    targetTitle: nil,
                    targetBody: "Other memo body"
                )
            ]
        )
        XCTAssertEqual(
            mapped,
            [
                PromoteEngine.LinkedIssue(
                    direction: "outgoing",
                    linkType: "relates",
                    targetId: 2,
                    targetType: "memo",
                    targetTitle: "Other memo body"
                )
            ]
        )
    }

    func testIncomingLinkSwapsTargetAndKeepsExplicitTitle() {
        let mapped = PromoteEngine.linkedIssues(
            memoId: 7,
            rows: [
                PromoteEngine.LinkRow(
                    sourceIssueId: 3,
                    targetIssueId: 7,
                    linkType: "derived_from",
                    targetType: "task",
                    targetTitle: "Task title",
                    targetBody: "task body ignored when title present"
                )
            ]
        )
        XCTAssertEqual(
            mapped,
            [
                PromoteEngine.LinkedIssue(
                    direction: "incoming",
                    linkType: "derived_from",
                    targetId: 3,
                    targetType: "task",
                    targetTitle: "Task title"
                )
            ]
        )
    }

    /// TS: `row.target_type ?? 'unknown'` and empty-string titles fall back
    /// to the (missing) body, i.e. "".
    func testMissingCounterpartColumnsProduceUnknownTypeAndEmptyTitle() {
        let mapped = PromoteEngine.linkedIssues(
            memoId: 1,
            rows: [
                PromoteEngine.LinkRow(
                    sourceIssueId: 1,
                    targetIssueId: 99,
                    linkType: "relates",
                    targetType: nil,
                    targetTitle: nil,
                    targetBody: nil
                )
            ]
        )
        XCTAssertEqual(mapped.first?.targetType, "unknown")
        XCTAssertEqual(mapped.first?.targetTitle, "")
    }

    /// TS treats an empty (non-null) title the same as null: fallback wins.
    func testEmptyExplicitTitleUsesBodyFallback() {
        let mapped = PromoteEngine.linkedIssues(
            memoId: 1,
            rows: [
                PromoteEngine.LinkRow(
                    sourceIssueId: 1,
                    targetIssueId: 2,
                    linkType: "child",
                    targetType: "article",
                    targetTitle: "",
                    targetBody: "  article   body  "
                )
            ]
        )
        XCTAssertEqual(mapped.first?.targetTitle, "article body")
    }
}
