import Foundation

/// A memo as stored in the iOS-local SQLite mirror. The ULID `id` is
/// generated by the device when the memo is captured offline and reused as
/// the server-side `clientId` once we sync, which lets us map the device's
/// stable identity to whatever INTEGER id the server assigns.
struct LocalMemo: Equatable {
    let id: String                  // ULID
    var serverId: Int64?            // nil until first sync
    var bodyMd: String
    var isBookmarked: Bool
    var isDeleted: Bool
    let createdAt: Date
    var updatedAt: Date
    var serverSyncedAt: Date?       // nil = pending

    var isPendingSync: Bool { serverSyncedAt == nil }

    /// Mirror of the server's API response — used by the SyncEngine to
    /// build the payload that gets POSTed. The encoder is configured to
    /// emit `clientId` (not `client_id`) because the server contract is
    /// camelCase JSON.
    struct CreatePayload: Codable {
        let clientId: String
        let bodyMd: String
    }

    func toCreatePayload() -> CreatePayload {
        CreatePayload(clientId: id, bodyMd: bodyMd)
    }
}
